telegram_token: ""
openai_api_key: ""
anthropic_api_key: ""
yookassa_shop_id: ""
yookassa_secret_key: ""
openai_api_base: null
allowed_telegram_usernames: []
new_dialog_timeout: 600
return_n_generated_images: 1
n_chat_modes_per_page: 5
image_size: "1024x1024"
enable_message_streaming: true
enable_detailed_logging: true
developer_username: [""]
database_timezone: ""

# prices in rubles
model_pricing:
  gpt-3.5-turbo:
    price_per_1000_input_tokens: 0.15
    price_per_1000_output_tokens: 0.30
  gpt-4:
    price_per_1000_input_tokens: 3.00
    price_per_1000_output_tokens: 6.00
  whisper:
    price_per_1_min: 0.45
  dalle-2:
    price_per_1_image: 1.50
  dalle-3:
    price_per_1_image: 4.00

role_deduction_rates:
  admin: 0
  beta_tester: 1.05
  friend: 0
  regular_user: 1.10
  trial_user: 1

roles:
  admin: []
  beta_tester: []
  friend: []
  regular_user: []
  trial_user: []