from __future__ import annotations
from typing import Protocol, Any, Sequence

class ChatProvider(Protocol):
    """Интерфейс чата."""
    async def chat(self, messages: Sequence[dict[str, str]], max_tokens: int, temperature: float = 0.7) -> str: ...

class ImageProvider(Protocol):
    """Интерфейс изображений."""
    async def generate(self, prompt: str) -> bytes: ...
    async def edit(self, image_bytes: bytes, instruction: str) -> bytes: ...
    async def add_people(self, image_bytes: bytes, description: str) -> bytes: ...
    async def celebrity_selfie(self, image_bytes: bytes, celebrity_name: str, style: str | None = None) -> bytes: ...
